export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const EDIT_SERVISE_DATA = 'EDIT_SERVISE_DATA';
export const EDIT_SERVISE_CANCEL = 'EDIT_SERVISE_CANCEL';